#include <adlb/adlb.h>

// Header generated by cmake containing Fortran/C mangling macros:
#include "fortran_c_mangling.h"

void ADLB_FC_GLOBAL(adlb_init, ADBL_INIT)(int *num_servers, int *use_debug_server,
                                          int *aprintf_flag, int *ntypes, int *type_vect,
                                          int *am_server, int *am_debug_server,
                                          MPI_Fint *app_comm, int *ierr) {
    MPI_Comm app_comm_out;
    *ierr = ADLB_Init(*num_servers, *use_debug_server, *aprintf_flag, *ntypes, type_vect,
                      am_server, am_debug_server, &app_comm_out);
    *app_comm = MPI_Comm_c2f(app_comm_out);
}

void ADLB_FC_GLOBAL(adlb_server, ADBL_SERVER)(double *hi_malloc,
                                              double *periodic_log_interval, int *ierr) {
    *ierr = ADLB_Server(*hi_malloc, *periodic_log_interval);
}

void ADLB_FC_GLOBAL(adlb_put, ADBL_PUT)(void *work_buf, int *work_len, int *reserve_rank,
                                        int *answer_rank, int *work_type, int *work_prio,
                                        int *ierr) {
    *ierr = ADLB_Put(work_buf, *work_len, *reserve_rank, *answer_rank, *work_type,
                     *work_prio);
}

void ADLB_FC_GLOBAL(adlb_reserve, ADBL_RESERVE)(int *req_types, int *work_type,
                                                int *work_prio, int *work_handle,
                                                int *work_len, int *answer_rank,
                                                int *ierr) {
    *ierr =
        ADLB_Reserve(req_types, work_type, work_prio, work_handle, work_len, answer_rank);
}

void ADLB_FC_GLOBAL(adlb_ireserve, ADBL_IRESERVE)(int *req_types, int *work_type,
                                                  int *work_prio, int *work_handle,
                                                  int *work_len, int *answer_rank,
                                                  int *ierr) {
    *ierr = ADLB_Ireserve(req_types, work_type, work_prio, work_handle, work_len,
                          answer_rank);
}

void ADLB_FC_GLOBAL(adlb_get_reserved, ADBL_GET_RESERVED)(void *work_buf,
                                                          int *work_handle, int *ierr) {
    *ierr = ADLB_Get_reserved(work_buf, work_handle);
}

void ADLB_FC_GLOBAL(adlb_get_reserved_timed,
                    ADLB_GET_RESERVED_TIMED)(void *work_buf, int *work_handle,
                                             double *qtime, int *ierr) {
    *ierr = ADLB_Get_reserved_timed(work_buf, work_handle, qtime);
}

void ADLB_FC_GLOBAL(adlb_begin_batch_put,
                    ADLB_BEGIN_BATCH_PUT)(void *common_buf, int *len_common, int *ierr) {
    *ierr = ADLB_Begin_batch_put(common_buf, *len_common);
}

void ADLB_FC_GLOBAL(adlb_end_batch_put, ADLB_END_BATCH_PUT)(int *ierr) {
    *ierr = ADLB_End_batch_put();
}

void ADLB_FC_GLOBAL(adlb_begin_batch_put_2, ADLB_BEGIN_BATCH_PUT_2)(void *common_buf,
                                                                    int *len_common,
                                                                    int *ierr) {
    *ierr = ADLB_Begin_batch_put(common_buf, *len_common);
}

void ADLB_FC_GLOBAL(adlb_end_batch_put_2, ADLB_END_BATCH_PUT_2)(int *ierr) {
    *ierr = ADLB_End_batch_put();
}

void ADLB_FC_GLOBAL(adlb_set_no_more_work,
                    ADLB_SET_NO_MORE_WORK)(int *ierr)  // deprecated
{
    *ierr = ADLB_Set_no_more_work();
}

void ADLB_FC_GLOBAL(adlb_set_problem_done, ADLB_SET_PROBLEM_DONE)(int *ierr) {
    *ierr = ADLB_Set_problem_done();
}

void ADLB_FC_GLOBAL(adlb_info_get, ADLB_INFO_GET)(int *key, double *val, int *ierr) {
    *ierr = ADLB_Info_get(*key, val);
}

void ADLB_FC_GLOBAL(adlb_info_num_work_units,
                    ADLB_INFO_NUM_WORK_UNITS)(int *work_type, int *max_prio,
                                              int *num_max_prio_type, int *num_type,
                                              int *ierr) {
    *ierr = ADLB_Info_num_work_units(*work_type, max_prio, num_max_prio_type, num_type);
}

void ADLB_FC_GLOBAL(adlb_finalize, ADLB_FINALIZE)(int *ierr) { *ierr = ADLB_Finalize(); }

void ADLB_FC_GLOBAL(adlb_debug_server, ADLB_DEBUG_SERVER)(double *timeout, int *ierr) {
    *ierr = ADLB_Debug_server(*timeout);
}

void ADLB_FC_GLOBAL(adlb_abort, ADLB_ABORT)(int *code, int *ierr) {
    *ierr = ADLB_Abort(*code);
}
